### ISSUE TITLE
Allow injecting custom feeddata instead of default data

### ISSUE THREAD

**Issue by bravecobra** [bravecobra/identityserver4.admin-helm#13]
We need a way to overwrite the seeddata and the configuration with whatever files the user wants to provide. 
And we'll use the default ones  if nothing is provided to seed. 
We also want the flag of the seeding to be able to be set.

Helm can not get the content of an external file directly: https://github.com/helm/helm/issues/3276
We can get the content of an external file like the following. The encoding and decoding is to solve the newline problem

So if we deploy like this:

```
helm install --set-file adminAppSettingsValues=./admin-appsettings.json
```
We can then apply that in the Chart like 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: <config-name>
data:
  appsettings.json: |-
  {{ .Values.adminAppSettingsValues}}`
```

and the based on the existence of `.Values.adminAppSettingsValues`, start the seeding from that content. We need to do that for each of the json files to allow overriding externally.
